### ISSUE TITLE
Ruby check requires Net::HTTP incorrectly

### ISSUE THREAD

**Issue by nate** [paypal/TLS-update#17]
The current check is:

```ruby -r'net/HTTP' -e 'uri = URI("https://tlstest.paypal.com/"); puts Net::HTTP.get(uri)'```

When it should be:

```ruby -r'net/http' -e 'uri = URI("https://tlstest.paypal.com/"); puts Net::HTTP.get(uri)'```

As an aside, it could be shortened a bit by going with:

```ruby -r'net/http' -e 'puts Net::HTTP.get(URI("https://tlstest.paypal.com/"))'```

**Comment by bluk** [comment]
I made the suggested shortened fix. Thanks for the correction.
