### ISSUE TITLE
braintree - undefined method ssl_version

### ISSUE THREAD

**Issue by murbano83** [paypal/TLS-update#25]
Hi!

When I set :TLSv1_2 on ruby i get this error:

```ruby
>> Braintree::Configuration.ssl_version = :TLSv1_2
=> :TLSv1_2
>> Braintree::ClientToken.generate
NoMethodError: undefined method `ssl_version=' for #<Net::HTTP api.sandbox.braintreegateway.com:443 open=false>
	from /home/murbano/vlex/vendor/bundle/ruby/1.8/gems/braintree-2.71.0/lib/braintree/http.rb:79:in `_http_do'
	from /home/murbano/vlex/vendor/bundle/ruby/1.8/gems/braintree-2.71.0/lib/braintree/http.rb:28:in `post'
	from /home/murbano/vlex/vendor/bundle/ruby/1.8/gems/braintree-2.71.0/lib/braintree/client_token_gateway.rb:17:in `generate'
	from /home/murbano/vlex/vendor/bundle/ruby/1.8/gems/braintree-2.71.0/lib/braintree/client_token.rb:8:in `generate'
	from (irb):12
```

How to fix it?

**Comment by bluk** [comment]
To support [TLS 1.2 in Ruby](https://github.com/paypal/TLS-update#ruby), you need to upgrade to a Ruby version >=2.0.0. It appears you are using Ruby 1.8 from the trace you have given. Earlier versions of Ruby do not support TLS 1.2 out of the box and [are not maintained anymore](https://www.ruby-lang.org/en/downloads/).

If you are using a Ruby version > 2.0 or have other questions, please leave a comment or open a new issue. Thanks!
