### ISSUE TITLE
.EXE's not compatible w/Windows Server 2012

### ISSUE THREAD

**Issue by austinjordan** [paypal/TLS-update#29]
https://github.com/paypal/TLS-update/tree/master/net

We are trying to run the executables on Windows Server 2012 (inside Azure server), but it states that the application is not compatible with this version of Windows.

Tried to run it on a person dev machine (localhost) just to try alternate method, which is running Windows 10, says the same thing.

**Comment by bluk** [comment]
You may have to rebuild the source in that same directory if you want to use the test apps.

However, the best way to test now is to use PayPal Sandbox. Sandbox was updated to only use [TLS 1.2 connections](https://www.paypal-notice.com/en/TLS-1.2-and-HTTP1.1-Upgrade/) last year.
