### ISSUE TITLE
Python testing needs to be improved, additional note regarding fail case, OSX how to fix?

### ISSUE THREAD

**Issue by trebor74hr** [paypal/TLS-update#3]
3 things:

1) I have noticed that following command for testing needs to be a bit improved: 

`python -c "import urllib2; urllib2.urlopen('https://tlstest.paypal.com/').read()"
`
to:

 `python -c "import urllib2; print(urllib2.urlopen('https://tlstest.paypal.com/').read())"
`

2) Other thing is that in my case due old OSX python ssl library is linked to old (official) OSX libssl version I get following error: 

`urllib2.URLError: <urlopen error [Errno 54] Connection reset by peer>`

It would be nice to add a remark to this kind of error.

3) I am encountering this problem on OSX 10.9.5 and 10.11 - where default openssl version is 0.9.8 which does not support TLS v 1.1+ (see previous note). What should I do to fix the problem?

**Comment by trebor74hr** [comment]
I think this is the root of the problem with OSX python ssl library version - linked to 0.9.8 libssl: 

```
python --version
Python 2.7.5

.../lib/python2.7/lib-dynload# otool -L _ssl.so
_ssl.so:
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 50.0.0)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 50.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)


```

**Comment by juwlee** [comment]
Thanks for the suggestion @trebor74hr . 1) and 2) have been updated, and it looks like you have found a solution to 3). I am closing this issue but please reopen or add a comment if necessary.

**Comment by trebor74hr** [comment]
Thanks for quick response, only thing I would suggest additionally is to add a remark that by default on OSX is installed openssl version 0.9.8 which does not support TLS 1.1+, and default python installation's library ssl is linked to this openssl version. Check can be done with: 

`python -c "import ssl; print ssl.OPENSSL_VERSION"`

and solution to the problem is explained at: http://stackoverflow.com/a/27230127/565525
