### ISSUE TITLE
php/cacert.pem outdated?

### ISSUE THREAD

**Issue by DerVO** [paypal/TLS-update#34]
I used your php-Check `TlsCheck.php` and get a response:

`SSL certificate problem: unable to get local issuer certificate`

With a different `cacert.pem` (taken from https://curl.haxx.se/ca/cacert.pem) it worked just fine. Is your CA-File just outdated?

**Comment by bluk** [comment]
@DerVO Thanks for the report. We will update this repository with the requirements from the [2017-2018 Merchant Security Roadmap Microsite](https://www.paypal-notice.com/en/) for the SSL upgrade.

**Comment by bluk** [comment]
I updated the cacert.pem to have the DigiCert root that was needed, so this should be fixed. Thanks.
