### ISSUE TITLE
ASP.NET MVC Request returns : (426) Unknown

### ISSUE THREAD

**Issue by okarpov** [paypal/TLS-update#36]
### General information

* Environment: Production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: C# ASP.NET MVC 5 on Windows Shared Hosting

### Issue description

`
 
        public ActionResult Test()
        {
            string res = "nothing";

            try
            {
                using (var wr = WebRequest.Create("https://tlstest.paypal.com").GetResponse())
                using (StreamReader streamIn = new StreamReader(wr.GetResponseStream()))
                {
                    res = "Test1: " + streamIn.ReadToEnd();
                }
            }
            catch (Exception ex)
            {
                res = "Test1: " + ex.ToString();
            }

            try
            {
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                using (var wr = WebRequest.Create("https://tlstest.paypal.com").GetResponse())
                using (StreamReader streamIn = new StreamReader(wr.GetResponseStream()))
                {
                    res += "Test2: " + streamIn.ReadToEnd();
                }
            }
            catch (Exception ex)
            {
                res += "Test2: " + ex.ToString();
            }

            return Content(res);
        }
 
`

The first check TLS1.2+HTTP/1.1 throws exception:

System.Net.WebException: The remote server returned an error: (426) Unknown. at System.Net.HttpWebRequest.GetResponse() at TTT.Controllers.PayPalController.Test() 

But after a few refreshes and minutes, it starts returning: PayPal_Connection_OK for both requests like:
Test1: PayPal_Connection_OKTest2: PayPal_Connection_OK

**Comment by bluk** [comment]
The 426 HTTP Status Code Error returned indicates that your connection wasn't using TLS 1.2 at that time. Does `Test2` always work? If you're using a proxy or anything else between your app and the HTTP request, I would also verify that it is properly updated.

You may also want to use the PayPal Sandbox which was [updated to only allow TLS 1.2 and HTTP/1.1](https://www.paypal-notice.com/en/TLS-1.2-and-HTTP1.1-Upgrade/).

**Comment by okarpov** [comment]
also, it seems that 
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

does not force to TLS12 and it might be better to use this code:

`System.Net.ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
System.Net.ServicePointManager.SecurityProtocol &= ~SecurityProtocolType.Ssl3;`

to force to TLS12

**Comment by bluk** [comment]
I'm not sure why it starts working after a few minutes. Will follow up with the PP infrastructure.

I would try to use PayPal Sandbox though at this point as another test endpoint to ensure that your app is ready.

**Comment by bluk** [comment]
Great, glad it is working. Your client may have been negotiating with something lower than TLS 1.2 sometimes which caused it to connect to the site and get a 426 response status code. I do highly recommend also testing with the PayPal sandbox since it has been changed for TLS 1.2 and HTTP/1.1 requirements.
